### ISSUE TITLE
RFE: App listing icon

### ISSUE THREAD

**Issue by amanthegreatone** [timoknapp/sound-on-fire#28] opened 2020-10-24 13:35 UTC
would be great if there was an icon to recognise the app in the list. right now the generic grey box is displayed and since there is no app name anywhere its difficult to recognise the app.

![PXL_20201024_131414433](https://user-images.githubusercontent.com/24354452/97083142-dcdfee80-162b-11eb-88f5-bb15f4f853aa.jpg)

**Comment by timoknapp** [comment] 2020-10-24 17:19
Hi @amanthegreatone ,

Which device are you using exactly? I could only test it on the FireTV 4K and  the regular FireTV and both showed me the actual App Icon of SoundOnFire.

Regards
Timo

**Comment by timoknapp** [comment] 2020-10-27 16:41
@smlabt does that screenshot show the UI of the Samsung Smart TV? It does not look like FireTV at all. If so, could you try it on your Samsung TV?

**Comment by amanthegreatone** [comment] 2020-11-16 10:44
@timoknapp i have the Fire TV Stick (3rd Generation)

**Comment by timoknapp** [comment] 2020-12-30 09:39
Hi @amanthegreatone ,

Could you try deleting the app and reinstalling it? I tested the installation on multiple Fire TV Sticks and could not reproduce this yet. Thanks!
Timo

**Comment by robsalasco** [comment] 2021-01-23 20:09
I don't have the icon too. I'm running on a Fire TV Cube (last gen)

**Comment by timoknapp** [comment] 2021-01-23 20:17
Hi @robsalasco ,

Thanks for the feedback. Could you maybe sent me screenshot of your firetv OS version? Should be in the settings.

Thanks!
Regards
Timo

**Comment by robsalasco** [comment] 2021-01-23 22:48
![WhatsApp Image 2021-01-23 at 7 47 16 PM](https://user-images.githubusercontent.com/2642107/105616186-e1937a80-5db3-11eb-9a9f-87f70bf62c6b.jpeg)

**Comment by timoknapp** [comment] 2021-01-24 16:19
Hi @robsalasco , @amanthegreatone 

I looked into this and there could be 2 reasons for the App Icon not being shown on your devices:

1. **Fire OS 7** (Android Pie, 9) [has issues](https://www.aftvnews.com/how-to-fix-missing-or-broken-icons-for-sideloaded-apps-on-amazon-fire-tv/) with showing App icons of side-loaded apps. Therefore I tweaked the configuration a little to check if this will help you. Since I do not have a Fire TV Cube to test with, it would be great if you could test the [new Version](https://github.com/timoknapp/sound-on-fire/suites/1889440800/artifacts/36948360) on your device. Please follow the instructions:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**1.1** Delete the current version of SoundOnFire (Settings > Apps > SoundOnFire > Delete App)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**1.2**  Download the [new Version](https://github.com/timoknapp/sound-on-fire/suites/1889440800/artifacts/36948360) and install it to your Fire TV Cube like you [did initially](https://github.com/timoknapp/sound-on-fire#getting-started).

**If this works for you**, I will publish the change with the **upcoming release of SoundOnFire** 👍 .

2. **If it does not help you**, then I guess it is related to [this](https://stackoverflow.com/a/51546241/13209526). Which basically means that the FireTV blocks side-loaded Apps to show their App Icons until they are submitted to the official Amazon App Store. I am not yet sure whether I actually plan to submit the App in the App Store.

Please let know If this helped you!

Regards
Timo

**Comment by robsalasco** [comment] 2021-01-25 00:29
Thank you @timoknapp now works! hope you can have time to improve the icon (it looks pixelated) :)

**Comment by timoknapp** [comment] 2021-01-25 06:41
Hi @robsalasco ,

Great that it helped. Could you please send me a screenshot again such that I get a feeling of how much I need to increase the resolution?

Regards
Timo

**Comment by robsalasco** [comment] 2021-01-25 14:34
![WhatsApp Image 2021-01-25 at 11 33 30 AM](https://user-images.githubusercontent.com/2642107/105719598-3abcf480-5f01-11eb-8417-12cf01850a52.jpeg)

**Comment by timoknapp** [comment] 2021-01-25 19:48
@robsalasco 

Thanks for the screenshot. I will have a further look and will try to change it to something more fancy 😄 
I will close the issue now, you should receive the new update via over the air whenever its released.

Have fun listening to SoundCloud! :)
Regards 
Timo

**Closed by timoknapp** 2021-01-25 19:48 UTC
